// Generates the COMPLETE gear catalog (every weapon, armor set, armor piece, ring, amulet and
// trinket in the game) from the asset paths scraped out of UE4SS_ObjectDump.txt.
// Emits: the native mod's tables, the UI's GEAR_CATALOG, and an id -> asset index that
// applyitemnames.js uses to swap placeholder labels for real in-game names.
// Usage: node tools/gengear.js tools/out-gear-paths.txt
const fs = require("fs");

const paths = fs
  .readFileSync(process.argv[2], "utf8")
  .split(/\r?\n/)
  .map((l) => l.trim())
  .filter((l) => l.startsWith("/Game/"));

const assetOf = (p) => p.split(".").pop();
const slotRe = /^ITM_Clothing_(Chest|Legs|Hands|Feet)(.+)$/;

// Placeholder label until the in-game name is dumped: split the CamelCase asset name into words.
const prettify = (raw) =>
  raw
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2")
    .trim();

const weapons = [];
const rings = [];
const amulets = [];
const trinkets = [];
const pieces = { Chest: [], Legs: [], Hands: [], Feet: [] };
const themes = new Map();

for (const path of paths) {
  const asset = assetOf(path);
  const slug = asset.replace(/^ITM_(Weapon|Clothing)_/, "").toLowerCase();

  if (asset.startsWith("ITM_Weapon_")) {
    weapons.push({ id: `weapon_${slug}`, asset, path, label: prettify(asset.replace("ITM_Weapon_", "")) });
    continue;
  }
  const slotMatch = slotRe.exec(asset);
  if (slotMatch) {
    const [, slot, theme] = slotMatch;
    pieces[slot].push({ id: `armor_${slug}`, asset, path, label: prettify(theme) });
    if (!themes.has(theme)) themes.set(theme, {});
    themes.get(theme)[slot] = path;
    continue;
  }
  if (/Ring|Signet/.test(asset)) {
    rings.push({ id: `ring_${slug}`, asset, path, label: prettify(asset.replace("ITM_Clothing_", "")) });
  } else if (/Amulet|Cross|Pendant/.test(asset)) {
    amulets.push({ id: `amulet_${slug}`, asset, path, label: prettify(asset.replace("ITM_Clothing_", "")) });
  } else {
    trinkets.push({ id: `trinket_${slug}`, asset, path, label: prettify(asset.replace("ITM_Clothing_", "")) });
  }
}

// Only themes with all four slots are offered as a set; the odd pieces stay individually grantable.
const SLOTS = ["Chest", "Legs", "Hands", "Feet"];
const sets = [...themes.entries()]
  .filter(([, slots]) => SLOTS.every((s) => slots[s]))
  .map(([theme, slots]) => ({
    id: `set_${theme.toLowerCase()}`,
    label: prettify(theme),
    paths: SLOTS.map((s) => slots[s]),
  }))
  .sort((a, b) => a.label.localeCompare(b.label));

const bySlug = (a, b) => a.label.localeCompare(b.label);
weapons.sort(bySlug);
rings.sort(bySlug);
amulets.sort(bySlug);
trinkets.sort(bySlug);
for (const slot of SLOTS) pieces[slot].sort(bySlug);

const singles = [...weapons, ...pieces.Chest, ...pieces.Legs, ...pieces.Hands, ...pieces.Feet, ...rings, ...amulets, ...trinkets];

// --- native tables -------------------------------------------------------------------------
const cppSingles = singles.map((e) => `        {"${e.id}", STR("${e.path}")},`).join("\n");
const cppSetArrays = sets
  .map(
    (s) =>
      `    const GearItem k${s.id.replace(/[^a-z0-9]/gi, "")}[] = {\n` +
      s.paths.map((p) => `        {STR("${p}"), true},`).join("\n") +
      `\n    };`,
  )
  .join("\n");
const cppSetOptions = sets
  .map((s) => {
    const v = `k${s.id.replace(/[^a-z0-9]/gi, "")}`;
    return `        {"${s.id}", ${v}, std::size(${v})},`;
  })
  .join("\n");

fs.writeFileSync("tools/out-gear.cpp-singles.txt", cppSingles);
fs.writeFileSync("tools/out-gear.cpp-setarrays.txt", cppSetArrays);
fs.writeFileSync("tools/out-gear.cpp-setoptions.txt", cppSetOptions);

// --- UI catalog ----------------------------------------------------------------------------
const jsCategory = (category, entries, note) =>
  `  {\n    category: ${JSON.stringify(category)},\n${note ? `    note: ${JSON.stringify(note)},\n` : ""}    options: [\n` +
  entries.map((e) => `      { value: "${e.id}", label: ${JSON.stringify(e.label)} },`).join("\n") +
  `\n    ],\n  },`;

const js =
  `// GENERATED by tools/gengear.js from the game's own asset list - do not hand-edit entries.\n` +
  `// Ids MUST match native-mods/DawnwalkerNativeFix/dllmain.cpp. Labels start out derived from the\n` +
  `// asset name and are replaced with real in-game names by tools/applyitemnames.js.\n` +
  `export const GEAR_CATALOG = [\n` +
  [
    jsCategory("Armor Set", sets, "Grants all four matching pieces and equips them."),
    jsCategory("Weapon", weapons),
    jsCategory("Chest", pieces.Chest),
    jsCategory("Legs", pieces.Legs),
    jsCategory("Hands", pieces.Hands),
    jsCategory("Feet", pieces.Feet),
    jsCategory("Ring", rings),
    jsCategory("Amulet", amulets),
    jsCategory("Trinket", trinkets),
  ].join("\n") +
  `\n];\n`;

fs.writeFileSync("tools/out-gear.js.txt", js);

// --- id -> asset index, for the name merger ------------------------------------------------
fs.writeFileSync(
  "tools/gear-index.json",
  JSON.stringify(Object.fromEntries(singles.map((e) => [e.id, e.asset])), null, 2),
);

console.log(
  `sets ${sets.length} | weapons ${weapons.length} | chest ${pieces.Chest.length} | legs ${pieces.Legs.length} | ` +
    `hands ${pieces.Hands.length} | feet ${pieces.Feet.length} | rings ${rings.length} | amulets ${amulets.length} | ` +
    `trinkets ${trinkets.length} | single entries ${singles.length}`,
);
